# Generated by Django 5.1 on 2024-12-01 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
        ('core_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplacementstorage',
            name='annoynmous_track',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymousbooking'),
        ),
    ]
