# Generated by Django 5.1 on 2024-12-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_control', '0001_initial'),
        ('core_payments', '0002_orderplacementstorage_annoynmous_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Check-in Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Check-out Date'),
        ),
        migrations.AlterField(
            model_name='orderplacementstorage',
            name='annoynmous_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core_control.anonymousbooking'),
        ),
    ]
