# Generated by Django 5.1 on 2024-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_payments', '0003_alter_order_check_in_alter_order_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_booking',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
