# Generated by Django 5.1 on 2024-08-29 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('suite', 'suite')], db_index=True, max_length=100)),
                ('description', models.TextField(db_index=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('room_amenities', models.CharField(db_index=True, max_length=100)),
                ('availabilty_from', models.DateField(default=None, null=True)),
                ('availabilty_till', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(db_index=True, upload_to='hotels/images')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('company_registration_number', models.PositiveBigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink')], db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('image', models.ImageField(db_index=True, upload_to='hotels/images')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
                ('company_registration_number', models.PositiveBigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('availabilty_from', models.DateField(default=None, null=True)),
                ('availabilty_till', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('comment', models.TextField(blank=True)),
                ('date_of_notice', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_posts.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
