# Generated by Django 5.1 on 2024-09-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_city_hotelimages_remove_hotel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='bedroom',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_posts.hotel'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='resturant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_posts.restaurant'),
        ),
        migrations.AddField(
            model_name='tables',
            name='resturant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_posts.restaurant'),
        ),
    ]
