# Generated by Django 5.1 on 2024-09-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0002_tables_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='review',
            name='tables_of_resturant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core_posts.tables'),
        ),
    ]
