# Generated by Django 5.1 on 2024-09-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0003_delete_city_bedroom_hotel_menuitem_resturant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_index=True, upload_to='hotels/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(db_index=True, default='', to='core_posts.hotelimages'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='images',
            field=models.ManyToManyField(db_index=True, default='', to='core_posts.resturantimages'),
        ),
    ]
