# Generated by Django 5.1 on 2024-09-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0004_resturantimages_remove_restaurant_image_hotel_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotelimages',
            name='hotel_image_id',
            field=models.CharField(db_index=True, default=None, max_length=100, unique=True),
        ),
    ]
