# Generated by Django 5.1 on 2024-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0005_cities_hotelimages_hotel_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturantimages',
            name='resturant_img_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bedroom',
            name='room_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='city_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelimages',
            name='hotel_image_id',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dish_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='resturant_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='resturantimages',
            name='image',
            field=models.ImageField(db_index=True, upload_to='resturant/images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tables',
            name='table_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
