# Generated by Django 5.1 on 2024-09-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0006_alter_tables_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='review',
        ),
        migrations.AddField(
            model_name='tables',
            name='review',
            field=models.ManyToManyField(blank=True, db_index=True, to='core_posts.review'),
        ),
    ]
