# Generated by Django 5.1 on 2024-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0007_alter_bedroom_room_id_alter_cities_city_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
