# Generated by Django 5.1 on 2024-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0007_remove_tables_review_tables_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='images',
            field=models.ImageField(db_index=True, default=None, null=True, upload_to='menu/images'),
        ),
    ]
