# Generated by Django 5.1 on 2024-09-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0008_menuitem_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='images',
            new_name='image',
        ),
    ]
