# Generated by Django 5.1 on 2024-09-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0008_alter_hotel_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='reviews',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core_posts.review'),
        ),
    ]
