# Generated by Django 5.1 on 2024-09-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0009_bedroom_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='reviews',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_posts.review'),
        ),
    ]
