# Generated by Django 5.1 on 2024-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0009_rename_images_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bedroom',
            name='room_amenities',
        ),
        migrations.AddField(
            model_name='bedroom',
            name='room_amenities',
            field=models.ManyToManyField(db_index=True, to='core_posts.amenities'),
        ),
    ]
