# Generated by Django 5.1 on 2024-10-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0010_amenities_remove_bedroom_room_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='room_amenities',
            field=models.ManyToManyField(db_index=True, related_name='bed_rooms', to='core_posts.amenities'),
        ),
    ]
