# Generated by Django 5.1 on 2024-09-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0010_alter_bedroom_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='image',
            field=models.ImageField(db_index=True, default=None, upload_to='beds/images'),
        ),
    ]
