# Generated by Django 5.1 on 2024-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0011_bedroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='image',
            field=models.ImageField(db_index=True, default=None, null=True, upload_to='beds/images'),
        ),
    ]
