# Generated by Django 5.1 on 2024-09-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0012_alter_bedroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
    ]
