# Generated by Django 5.1 on 2024-10-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0013_remove_favouritelist_fav_bed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
