# Generated by Django 5.1 on 2024-09-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0013_alter_hotel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='visitors',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_posts.cities'),
        ),
    ]
