# Generated by Django 5.1 on 2024-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0014_tables_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='available_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
