# Generated by Django 5.1 on 2024-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0015_review_room_alter_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
