# Generated by Django 5.1 on 2024-10-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0015_tables_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='available_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
