# Generated by Django 5.1 on 2024-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0018_reviewtype_remove_review_rating_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtype',
            name='name',
            field=models.CharField(choices=[('Cleanliness', 'Cleanliness'), ('Accuracy of information', 'Accuracy of information'), ('Communication', 'Communication'), ('Reception team', 'Reception team'), ('Experience de check-in', 'Experience de check-in'), ('Value', 'Value')], db_index=True, max_length=100),
        ),
    ]
