# Generated by Django 5.1 on 2024-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0020_remove_review_rating_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ManyToManyField(db_index=True, to='core_posts.reviewtype'),
        ),
    ]
