# Generated by Django 5.1 on 2024-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_posts', '0021_remove_review_rating_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedroom',
            name='reviews',
        ),
        migrations.AddField(
            model_name='bedroom',
            name='reviews',
            field=models.ManyToManyField(db_index=True, to='core_posts.review'),
        ),
    ]
